zabbix_api_url: "http://localhost/zabbix/api_jsonrpc.php"

zabbix_api_user: "Admin"
zabbix_api_password: "zabbix"

zabbix_megatp_group_name: "MegaTP"
zabbix_linux_template_name: "Linux by Zabbix agent"

zabbix_vip_host: "vip"
zabbix_vip_ip: "{{ vip_ip | default('192.168.56.100') }}"
zabbix_vip_item_key: "net.tcp.service[http,,80]"
zabbix_vip_item_name: "VIP HTTP service"
zabbix_vip_trigger_name: "VIP HTTP DOWN"

zabbix_dashboard_name: "MegaTP - Dashboard"
